### ISSUE TITLE
gui support on chromebook

### ISSUE THREAD

**Issue by darkoverlordofdata** [mclarenlabs/libs-mclaren-alpha#15]
I've been trying this out on my Chromebook, and the problem I run into is gui. The menu's all stack up in the center of the screen. I can move the app window to my secondary monitor, but even then the menu selections don't always show up and I end up using alt-keys

![Screenshot 2024-09-08 3 21 53 PM](https://github.com/user-attachments/assets/94bf036f-01f2-4837-a3ed-c7ad5d39cbb2)

**Comment by mclarenlabs** [comment]
Hi Dark -

This is pretty frustrating, I know.  The Chromebook Linux environment is actually a really great development environment, but the integration with the Chromebook window manager is not quite right for GNUstep apps.  My experience with a GTK-based app is that integration is nearly flawless, but not so for GNUstep.

GNUstep applications want to manage window position in some way that the Chromebook WM doesn't understand.  (I suspect it has something to do with WM_HINTS property in X11, but I don't know enough about that.  Note that when you open the MskMetroDemo is is always in the center of the screen.  If it was working properly, it would open in the position where you last left it.  The menus are behaving the same way - always right in the center of the screen.

The workaround I've developed is to launch a separate X11 session in a window where all of the GNUstep development is running.  In this X11 environment, WindowMaker is the window manager and it understands GNUstep.

I make the X11 window Fullscreen, and then move it to a separate Desktop.   Use the "[ ]||" key to show the desktops, and then drag the Xephyr window onto Desktop 2.  (Or on to your external monitor.)

Then I can use the CMD-[ and CMD-] keys to move between the Chrome desktop and the X11/GNUstep desktop.  See the screenshot below for what it looks like running Xephyr with WMaker window manager, gs-terminal and the MskMetroDemo app.

![Screenshot 2024-09-09 7 33 15 AM](https://github.com/user-attachments/assets/ebd9db54-2481-4446-9d20-943dca84c737)

In this configuration, audio is passed through Pulse or Pipewire to the Chromebook sound server and the X11 window is rendering the GUI.

Attached is the script (named "startgs1") I use to get the full-screen window going.  (Remove the ".txt" suffix and make it executable  --- "chmod +x ./startgs1").  Then run it in a Linux terminal.

[startgs.txt](https://github.com/user-attachments/files/16932325/startgs.txt)

Let me know if this works for you.  I've found it to be a pretty nice way to work, keeping the GNUstep apps separate.

**Comment by mclarenlabs** [comment]
P.S. - for some reason I couldn't upload the executable shell script from the Chromebook environment.  Hence, the renaming with the ".txt" extension to get it into GitHub here.

**Comment by darkoverlordofdata** [comment]
Ok, I've used WindowMaker before, but never that way - brilliant! For an
application this narrowly focused it's almost a feature.

Thanks, I'll remember this trick. I haven't found many window managers that
play well with gnustep, but this is the worst.

**Comment by mclarenlabs** [comment]
:-)  Hope it does for you too.

This works pretty well for me.  You have all the nice security and integration of the Chromebook desktop, and then a separate desktop for developing GS apps in.

**Comment by darkoverlordofdata** [comment]
I've gotten this install and run perfectly, along with your software, on
both machines - an old Dell Inspiron running ChromeOS Flex, and on my
Chromebook Lenovo Duet II, which runs on arm!
